### ISSUE TITLE
Investigate lack of tuna + teriyaki sauce recipes

### ISSUE THREAD

**Issue by jayaddison** [openculinary/backend#24]
**Describe the bug**
As reported by user `zmix` on HN - https://news.ycombinator.com/item?id=24633174 - search results for `tuna` and `teriyaki sauce` are not returning results that contain both ingredients currently.

I'd expect we have already crawled recipes that contain tuna and teriyaki sauce, and that they should appear in search results.  This report could be an indication of a problem handling those ingredients and/or recipes.

Indeed, we seem to have crawled at least a few potential candidate recipes:

```sql
api=> select r.title, r.src
from recipes as r
join recipe_ingredients as ri_tuna on ri_tuna.recipe_id = r.id
join recipe_ingredients as ri_teriyaki on ri_tuna.recipe_id = ri_teriyaki.recipe_id
where ri_tuna.description like '%tuna%'
and ri_teriyaki.description like '%teriyaki%';

            title            |                                  src                                  
-----------------------------+-----------------------------------------------------------------------
 Teriyaki Tuna               | http://allrecipes.com/Recipe/Teriyaki-Tuna/Detail.aspx
 Tuna From Can To Frying Pan | http://allrecipes.com/Recipe/Tuna-From-Can-To-Frying-Pan/Detail.aspx
 Mack's Tunaburgers          | https://www.allrecipes.com/recipe/99241/macks-tunaburgers/
 Mack's Tunaburgers          | http://allrecipes.com/Recipe/Macks-Tunaburgers/Detail.aspx
 Teriyaki Tuna Burgers       | https://tastykitchen.com/recipes/main-courses/teriyaki-tuna-burgers/
 Teriyaki Tuna               | https://www.allrecipes.com/recipe/69617/teriyaki-tuna/
 Tuna From Can To Frying Pan | https://www.allrecipes.com/recipe/193497/tuna-from-can-to-frying-pan/
 Grilled Teriyaki Tuna       | http://allrecipes.com/Recipe/Grilled-Teriyaki-Tuna/Detail.aspx
 Grilled Teriyaki Tuna       | https://www.allrecipes.com/recipe/23039/grilled-teriyaki-tuna/
(9 rows)
```

**To Reproduce**
1. Perform the following search: https://www.reciperadar.com/#search&action=search&include=tuna,teriyaki%20sauce
2. Observe that no results are found containing all the query ingredients

**Expected behavior**
Some of the above-listed recipes should be displayed.

**Comment by jayaddison** [comment]
The next step is to check whether the ingredient descriptions were parsed into recipe language markup successfully.

It looks like four of the above recipes have associated markup for both ingredients:

```sql
api=> select r.title, ri_tuna.markup as tuna_markup, ri_teriyaki.markup as teriyaki_markup
from recipes as r
join recipe_ingredients as ri_tuna on ri_tuna.recipe_id = r.id
join recipe_ingredients as ri_teriyaki on ri_tuna.recipe_id = ri_teriyaki.recipe_id
where ri_tuna.description like '%tuna%'
and ri_teriyaki.description like '%teriyaki%'
and ri_tuna.markup is not null
and ri_teriyaki.markup is not null;

            title            |                                            tuna_markup                                             |                                  teriyaki_markup                                   
-----------------------------+----------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------
 Grilled Teriyaki Tuna       | <amt><qty>453.59</qty><unit>g</unit></amt>fillets yellowfin <ingredient>tuna</ingredient>          | <amt><qty>236.59</qty><unit>ml</unit></amt><ingredient>teriyaki sauce</ingredient>
 Teriyaki Tuna               | <amt><qty>680.39</qty><unit>g</unit></amt>sashimi grade <ingredient>tuna steaks</ingredient>       | <amt><qty>118.29</qty><unit>ml</unit></amt><ingredient>teriyaki sauce</ingredient>
 Mack's Tunaburgers          | <amt><qty>141.75</qty><unit>g</unit></amt>can water-packed <ingredient>tuna</ingredient>, drained  | <amt><qty>59.15</qty><unit>ml</unit></amt><ingredient>teriyaki sauce</ingredient>
 Tuna From Can To Frying Pan | <amt><qty>141.75</qty><unit>g</unit></amt>can <ingredient>tuna</ingredient> packed in oil, drained | <amt><qty>14.79</qty><unit>ml</unit></amt><ingredient>teriyaki sauce</ingredient>
(4 rows)
```

**Comment by jayaddison** [comment]
The `Grilled Teriyaki Tuna` recipe seems to have been (re)crawled correctly after I re-posted it to the `backend` service:

```sh
$ curl -H 'Host: backend' -XPOST localhost:30080/recipes/crawl --data 'url=https://www.allrecipes.com/recipe/23039/grilled-teriyaki-tuna/'
```

That's fine I suppose, although it would be good to determine whether any other recipes need to be reindexed in the same manner.

It's now visible on the site -- and is easiest to find when sorting by 'relevance'.  It could be time to evaluate and revisit the default sort algorithm soon.

https://www.reciperadar.com/#search&action=search&include=tuna,teriyaki%20sauce&sort=relevance

**Comment by jayaddison** [comment]
The `crawler` service is returning an HTTP 500 for `Tuna From Can To Frying Pan` which likely explains why it has not been indexed.

The container logs aren't initially hugely helpful in determining the cause:

```sh
$ kubectl logs -f deployments/crawler-deployment
[2020-09-29 22:31:26,342] ERROR in app: Exception on /crawl [POST]
Traceback (most recent call last):
  File "/srv/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/srv/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/web/app.py", line 158, in crawl
    ingredients = parse_ingredients(scrape.ingredients())
  File "/web/app.py", line 51, in parse_ingredients
    ingredients = requests.post(
  File "/srv/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by jayaddison** [comment]
Thanks to openculinary/crawler#14, the problem has been narrowed down to a parser failure for the following ingredients:

```sh
$ curl -H 'Host: crawler' -XPOST localhost:30080/crawl --data 'url=https://www.allrecipes.com/recipe/193497/tuna-from-can-to-frying-pan/'
{"error":{"message":"ingredient parsing failed for: ['2 cups broccoli florets', '2 tablespoons butter', '1 pinch salt and pepper to taste', '1 (5 ounce) can tuna packed in oil, drained', '1 tablespoon teriyaki sauce', '1 pinch garlic powder']"}}
```

It particular it looks like it was the garlic powder line that caused a problem here.

```sh
$ curl -s -H 'Host: ingredient-parser' -XPOST localhost:30080 --data 'descriptions[]=1 pinch garlic powder' | jq
parse error: Invalid numeric literal at line 1, column 10
```

**Comment by jayaddison** [comment]
The coverage situation for these ingredients can be improved further (by finding and crawling more recipes from the web), but the set of nine already-crawled recipes found above reduces down to four unique recipes, and three of those are now indexed.

openculinary/knowledge-graph#50 will be tracked and resolved separately, and relates to the last of the four recipes mentioned.
